# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budgethead_recurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='fiscal_year',
            field=models.PositiveIntegerField(choices=[(2069, b'2069/70'), (2070, b'2070/71'), (2071, b'2071/72'), (2072, b'2072/73'), (2073, b'2073/74')], default=2073),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='year',
            field=models.IntegerField(choices=[(2069, b'2069/70'), (2070, b'2070/71'), (2071, b'2071/72'), (2072, b'2072/73'), (2073, b'2073/74')], unique=True),
        ),
    ]
