# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160703_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='fiscal_year',
            field=models.PositiveIntegerField(choices=[(2069, b'2069/70'), (2070, b'2070/71'), (2071, b'2071/72'), (2072, b'2072/73'), (2073, b'2073/74')], default=2073),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='year',
            field=models.IntegerField(choices=[(2069, b'2069/70'), (2070, b'2070/71'), (2071, b'2071/72'), (2072, b'2072/73'), (2073, b'2073/74')], unique=True),
        ),
    ]
