# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ils', '0003_auto_20160611_1344'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subject',
            managers=[
            ],
        ),
    ]
