# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthr',
            name='allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_reports', to='hr.AllowanceName'),
        ),
        migrations.AddField(
            model_name='reporthr',
            name='incentive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incentive_reports', to='hr.IncentiveName'),
        ),
        migrations.AlterField(
            model_name='reporthr',
            name='deduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_reports', to='hr.DeductionName'),
        ),
    ]
