# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20170124_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancename',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='allowancename',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deductionname',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deductionname',
            name='name_ne',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='designation_name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='designation_name_ne',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_ne',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='grade_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='grade_name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeegradegroup',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeegradegroup',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incentivename',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incentivename',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
