# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20170124_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthr',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='hr.TaxDeduction'),
        ),
        migrations.AddField(
            model_name='taxdeduction',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taxdeduction',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
