# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20170125_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthr',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporthr',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
