# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20170125_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttable',
            name='table_fields',
        ),
        migrations.AddField(
            model_name='reporttable',
            name='table_json',
            field=models.FilePathField(match=b'.*\\.json$', null=True, path=b'/home/wrufesh/git/nerp/hr/templates/report_templates/report_table_jsons'),
        ),
    ]
