# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20170126_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttable',
            name='table_json',
            field=models.FilePathField(default=1, match=b'.*\\.json$', path=b'/home/wrufesh/git/nerp/hr/templates/report_templates/report_table_jsons'),
            preserve_default=False,
        ),
    ]
