# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 06:50
from __future__ import unicode_literals

from django.db import migrations
import hr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20170126_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='entry_date',
            field=hr.fields.HRBSDateField(default=hr.fields.today),
        ),
    ]
