# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_payrollentry_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollentry',
            name='entry_rows',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entry_rows', to='hr.PayrollEntry'),
            preserve_default=False,
        ),
    ]
