# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_auto_20170126_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='allowance_details',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='deduction_details',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='incentive_details',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='pro_tempore_details',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='tax_details',
        ),
        migrations.AddField(
            model_name='allowancedetail',
            name='payment_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_details', to='hr.PaymentRecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deductiondetail',
            name='payment_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_details', to='hr.PaymentRecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivedetail',
            name='payment_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incentive_details', to='hr.PaymentRecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protemporedetail',
            name='payment_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pro_tempore_details', to='hr.PaymentRecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxdetail',
            name='payment_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_details', to='hr.PaymentRecord'),
            preserve_default=False,
        ),
    ]
