# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-29 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_auto_20170127_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancename',
            name='code_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deductionname',
            name='code_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivename',
            name='code_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxdeduction',
            name='code_name',
            field=models.CharField(choices=[(b'Remuneration Tax', 'Remuneration Tax'), (b'Social Security Tax', 'Social Security Tax')], default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allowancename',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='allowancename',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='allowancename',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='deductionname',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='deductionname',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deductionname',
            name='name_ne',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incentivename',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incentivename',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incentivename',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxdeduction',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taxdeduction',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxdeduction',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
