# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_auto_20170129_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
