# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-07 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_auto_20170131_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthr',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='reporthr',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='reporthr',
            name='incentive',
        ),
        migrations.RemoveField(
            model_name='reporthr',
            name='tax',
        ),
    ]
