# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-12 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_auto_20170207_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTableDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=250)),
                ('field_description', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reporttable',
            name='table_json',
        ),
    ]
