# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-03 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_auto_20170203_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporthr',
            old_name='allowance',
            new_name='allowances',
        ),
        migrations.RenameField(
            model_name='reporthr',
            old_name='deduction',
            new_name='deductions',
        ),
        migrations.RenameField(
            model_name='reporthr',
            old_name='incentive',
            new_name='incentives',
        ),
        migrations.RenameField(
            model_name='reporthr',
            old_name='tax',
            new_name='taxes',
        ),
    ]
