# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-12 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_auto_20170212_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttabledetail',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table_details', to='hr.ReportTable'),
            preserve_default=False,
        ),
    ]
