# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_auto_20170203_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_query', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='reporthr',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='reporthr',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='reporthr',
            name='incentives',
        ),
        migrations.RemoveField(
            model_name='reporthr',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='reporttable',
            name='table_json',
        ),
        migrations.AlterUniqueTogether(
            name='allowancedetail',
            unique_together=set([('allowance', 'payment_record')]),
        ),
        migrations.AlterUniqueTogether(
            name='deductiondetail',
            unique_together=set([('deduction', 'payment_record')]),
        ),
        migrations.AlterUniqueTogether(
            name='incentivedetail',
            unique_together=set([('incentive', 'payment_record')]),
        ),
        migrations.AlterUniqueTogether(
            name='taxdetail',
            unique_together=set([('tax_deduction', 'payment_record')]),
        ),
        migrations.AddField(
            model_name='reporttablefield',
            name='report_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_fields', to='hr.ReportTable'),
        ),
    ]
