# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-12 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_reporttabledetail_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttabledetail',
            name='need_total',
            field=models.BooleanField(default=False),
        ),
    ]
