# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_reporttabledetail_need_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reporttabledetail',
            unique_together=set([('order', 'table')]),
        ),
    ]
