# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_auto_20170224_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='address_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='address_ne',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
