# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_auto_20170224_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthr',
            name='for_employee_type',
        ),
    ]
