# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_remove_reporthr_for_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='name_ne',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
