# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_employee_insurance_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfig',
            name='organization_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='unmarried_remuneration_discount',
            field=models.FloatField(default=300000.0, verbose_name='Remuneration tax discount for unmarried employee on taxable amount.'),
        ),
    ]
