# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_auto_20170301_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfig',
            name='organization_title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payrollconfig',
            name='organization_title_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
