# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_auto_20170301_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='citizen_investment_id_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
