# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0114_auto_20160602_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='with_temporary_employee',
        ),
    ]
