# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 10:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0115_remove_deduction_with_temporary_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('template_path', models.FilePathField(path=b'/home/wrufesh/git/nerp/hr/report_templates')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('table_fields', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.ReportHR')),
            ],
        ),
    ]
