# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0116_reporthr_reporttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthr',
            name='template_path',
        ),
        migrations.AddField(
            model_name='reporthr',
            name='template',
            field=models.FilePathField(default='/home/wrufesh', match=b'.*\\.html$', path=b'/home/wrufesh/git/nerp/hr/report_templates'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporttable',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_report', to='hr.ReportHR'),
        ),
    ]
