# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0117_auto_20160724_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthr',
            name='template',
            field=models.FilePathField(match=b'.*\\.html$', path=b'/home/wrufesh/git/nerp/hr/templates/report_templates'),
        ),
        migrations.AlterField(
            model_name='reporttable',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tables', to='hr.ReportHR'),
        ),
    ]
