# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0119_auto_20160727_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttable',
            name='table_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
