# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0120_auto_20160727_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttable',
            name='report',
        ),
        migrations.DeleteModel(
            name='ReportTable',
        ),
    ]
