# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 13:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0121_auto_20160730_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('table_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tables', to='hr.ReportHR')),
            ],
        ),
    ]
