# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 14:06
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0122_reporttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttable',
            name='table_fields',
            field=jsonfield.fields.JSONField(),
        ),
    ]
