# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0123_auto_20160819_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGradeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
