# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0124_employeegradegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegrade',
            name='parent_grade',
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='grade_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeeGradeGroup'),
        ),
    ]
