# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0125_auto_20160820_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowance',
            old_name='amount',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='deduction',
            old_name='amount',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='incentive',
            old_name='amount',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='allowance',
            name='amount_rate',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='amount_rate',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='amount_rate',
        ),
    ]
