# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0126_auto_20160822_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='add2_init_salary',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='permanent_multiply_rate',
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_refundable_deduction',
            field=models.BooleanField(default=False),
        ),
    ]
