# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 11:29
from __future__ import unicode_literals

from django.db import migrations
import njango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0127_auto_20160828_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='scale_start_date',
            field=njango.fields.BSDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='appoint_date',
            field=njango.fields.BSDateField(blank=True, default=njango.fields.today, null=True),
        ),
    ]
