# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import njango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0128_auto_20160915_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', njango.fields.BSDateField()),
                ('note', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGradeValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', njango.fields.BSDateField()),
                ('note', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='deduction',
            name='validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.DeductionValidity'),
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeeGradeValidity'),
        ),
    ]
