# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0129_auto_20160918_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGradeScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_scale', models.FloatField()),
                ('grade_number', models.PositiveIntegerField()),
                ('grade_rate', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employeegrade',
            name='grade_number',
        ),
        migrations.RemoveField(
            model_name='employeegrade',
            name='grade_rate',
        ),
        migrations.RemoveField(
            model_name='employeegrade',
            name='salary_scale',
        ),
        migrations.RemoveField(
            model_name='employeegrade',
            name='validity',
        ),
        migrations.AddField(
            model_name='employeegradescale',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeeGrade'),
        ),
        migrations.AddField(
            model_name='employeegradescale',
            name='validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeeGradeValidity'),
        ),
    ]
