# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0130_auto_20160918_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeGradeValidity',
            new_name='EmployeeGradeScaleValidity',
        ),
        migrations.AlterField(
            model_name='employeegrade',
            name='grade_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_grades', to='hr.EmployeeGradeGroup'),
        ),
        migrations.AlterField(
            model_name='employeegradescale',
            name='validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='hr.EmployeeGradeScaleValidity'),
        ),
    ]
