# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0131_auto_20160918_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegradescalevalidity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
