# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import njango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0132_employeegradescalevalidity_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScaleValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', njango.fields.BSDateField()),
                ('note', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='EmployeeGradeScaleValidity',
            new_name='AllowanceValidity',
        ),
        migrations.AddField(
            model_name='allowance',
            name='validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hr.AllowanceValidity'),
        ),
        migrations.AlterField(
            model_name='employeegradescale',
            name='validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='hr.GradeScaleValidity'),
        ),
        migrations.AlterUniqueTogether(
            name='employeegradescale',
            unique_together=set([('validity', 'grade')]),
        ),
    ]
