# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0133_auto_20161002_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradescalevalidity',
            name='is_active',
        ),
    ]
