# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0134_remove_gradescalevalidity_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegradescale',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='hr.EmployeeGrade'),
        ),
    ]
