# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20161018_1209'),
        ('hr', '0135_auto_20161005_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('priority', models.IntegerField(unique=True)),
                ('is_refundable_deduction', models.BooleanField(default=False)),
                ('is_tax_free', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False)),
                ('amount_editable', models.BooleanField(default=False)),
                ('deduct_in_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='amount_editable',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='deduct_in_category',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='is_optional',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='is_refundable_deduction',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='is_tax_free',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='priority',
        ),
        migrations.AlterField(
            model_name='deduction',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.DeductionName'),
        ),
    ]
