# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0136_auto_20161020_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
