# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0137_auto_20161021_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='value',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
