# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 07:17
from __future__ import unicode_literals

from django.db import migrations
import hr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0138_auto_20161021_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancevalidity',
            name='valid_from',
            field=hr.fields.HRBSDateField(),
        ),
        migrations.AlterField(
            model_name='deductionvalidity',
            name='valid_from',
            field=hr.fields.HRBSDateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='appoint_date',
            field=hr.fields.HRBSDateField(blank=True, default=hr.fields.today, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismiss_date',
            field=hr.fields.HRBSDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='scale_start_date',
            field=hr.fields.HRBSDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradescalevalidity',
            name='valid_from',
            field=hr.fields.HRBSDateField(),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_from_date',
            field=hr.fields.HRBSDateField(),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_to_date',
            field=hr.fields.HRBSDateField(),
        ),
        migrations.AlterField(
            model_name='protempore',
            name='appoint_date',
            field=hr.fields.HRBSDateField(default=hr.fields.today),
        ),
        migrations.AlterField(
            model_name='protempore',
            name='dismiss_date',
            field=hr.fields.HRBSDateField(blank=True, null=True),
        ),
    ]
