# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0139_auto_20161024_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancevalidity',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='employee',
            name='optional_deductions',
            field=models.ManyToManyField(blank=True, to='hr.DeductionName'),
        ),
    ]
