# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0140_auto_20161024_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductiondetail',
            name='deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduced_amount_detail', to='hr.DeductionName'),
        ),
    ]
