# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0141_auto_20161115_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Wrufesh Singh', max_length=128),
            preserve_default=False,
        ),
    ]
