# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0142_auto_20161117_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancename',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deductionname',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='incentivename',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
