# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0143_auto_20161117_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowancevalidity',
            options={'verbose_name_plural': 'Allowance Validities'},
        ),
        migrations.AlterModelOptions(
            name='deductionvalidity',
            options={'verbose_name_plural': 'Deduction Validities'},
        ),
        migrations.AlterModelOptions(
            name='gradescalevalidity',
            options={'verbose_name_plural': 'Grade Scale Validities'},
        ),
        migrations.AlterUniqueTogether(
            name='allowance',
            unique_together=set([('name', 'employee_grade', 'validity')]),
        ),
    ]
