# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0144_auto_20161119_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='designation',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='hr.Designation'),
            preserve_default=False,
        ),
    ]
