# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0146_auto_20161121_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_can_generate_payroll', models.BooleanField(default=False)),
                ('hr_calendar', models.CharField(choices=[(b'BS', b'BS'), (b'AD', b'AD')], max_length=2)),
            ],
            options={
                'verbose_name': 'Payroll Configuration',
            },
        ),
    ]
