# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0147_payrollconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_branch',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.BranchOffice'),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='hr_calendar',
            field=models.CharField(choices=[(b'BS', b'BS'), (b'AD', b'AD')], default=b'BS', max_length=2),
        ),
    ]
