# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 16:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0148_auto_20161121_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_branch',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_employees', to='hr.BranchOffice'),
        ),
        migrations.AlterField(
            model_name='payrollaccountant',
            name='branch',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_accountants', to='hr.BranchOffice'),
        ),
    ]
