# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 16:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0149_auto_20161121_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollentry',
            name='branch',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='hr.BranchOffice'),
            preserve_default=False,
        ),
    ]
