# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0152_auto_20161122_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_permanent',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[(b'PERMANENT', 'Permanent'), (b'TEMPORARY', 'Temporary')], default='PERMANENT', max_length=128),
            preserve_default=False,
        ),
    ]
