# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0153_auto_20161124_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_type',
            new_name='type',
        ),
    ]
