# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0154_auto_20161124_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[(b'ACTIVE', 'Active'), (b'INACTIVE', 'Inactive'), (b'SALARY_PUSED', 'Salary Paused')], default=b'ACTIVE', max_length=128),
        ),
    ]
