# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0155_auto_20161125_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='payment_halt',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_monthly_deduction_amount',
        ),
    ]
