# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 22:49
from __future__ import unicode_literals

from django.db import migrations
import hr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0156_auto_20161125_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appoint_date',
            field=hr.fields.HRBSDateField(blank=True, null=True),
        ),
    ]
