# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0159_remove_protempore_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protempore',
            old_name='pro_tempore',
            new_name='pro_tempore_employee',
        ),
    ]
