# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0160_auto_20161125_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deductionname',
            old_name='is_refundable_deduction',
            new_name='first_add_to_salary',
        ),
    ]
