# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0161_auto_20161127_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancename',
            name='is_tax_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incentivename',
            name='is_tax_free',
            field=models.BooleanField(default=False),
        ),
    ]
