# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0162_auto_20161127_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductiondetail',
            name='amount_added_before_deduction',
            field=models.FloatField(default=0.0),
        ),
    ]
