# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0163_deductiondetail_amount_added_before_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancename',
            name='status',
            field=models.CharField(choices=[(b'ACTIVE', 'Active'), (b'INACTIVE', 'Inactive')], default=b'ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='deductionname',
            name='status',
            field=models.CharField(choices=[(b'ACTIVE', 'Active'), (b'INACTIVE', 'Inactive')], default=b'ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='incentivename',
            name='status',
            field=models.CharField(choices=[(b'ACTIVE', 'Active'), (b'INACTIVE', 'Inactive')], default=b'ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='allowancename',
            name='account_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Category'),
        ),
        migrations.AlterField(
            model_name='deductionname',
            name='deduct_in_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Category'),
        ),
        migrations.AlterField(
            model_name='incentivename',
            name='account_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Category'),
        ),
    ]
