# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0164_auto_20161127_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancename',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deductionname',
            name='status',
        ),
        migrations.RemoveField(
            model_name='incentivename',
            name='status',
        ),
    ]
