# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0166_auto_20161128_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protempore',
            name='status',
            field=models.CharField(choices=[(b'REGISTERED', 'Registered'), (b'READY_FOR_PAYMENT', 'Ready for Payment'), (b'PAID', 'Paid')], default=b'REGISTERED', max_length=128),
        ),
    ]
