# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0168_employee_grade_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGradeNumberPause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', hr.fields.HRBSDateField()),
                ('to_date', hr.fields.HRBSDateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_number_pause_details', to='hr.Employee')),
            ],
        ),
    ]
