# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0169_employeegradenumberpause'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='address',
            field=models.CharField(default='this is branch address', max_length=256),
            preserve_default=False,
        ),
    ]
