# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0170_branchoffice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pf_id_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
