# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0172_reporthr_for_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthr',
            name='for_employee_type',
            field=models.CharField(choices=[(b'PERMANENT', 'Permanent'), (b'TEMPORARY', 'Temporary'), (b'ALL', 'All Type')], max_length=50),
        ),
    ]
