# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0173_auto_20161130_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthr',
            name='deduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hr.DeductionName'),
        ),
    ]
