# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import hr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0174_reporthr_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='scale_start_date',
            field=hr.fields.HRBSDateField(default=datetime.datetime(2016, 12, 4, 6, 3, 40, 158542, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
