# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20161115_1510'),
        ('hr', '0176_auto_20161204_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('account_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Category')),
            ],
        ),
    ]
