# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0178_employeefacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_facilities',
            field=models.ManyToManyField(to='hr.EmployeeFacility'),
        ),
    ]
