# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0179_employee_employee_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_facilities',
            new_name='facilities',
        ),
    ]
