# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0180_auto_20161204_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='yearly_insurance_premium',
            field=models.FloatField(default=0.0),
        ),
    ]
