# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0181_employee_yearly_insurance_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfig',
            name='disabled_remuneration_additional_discount',
            field=models.FloatField(default=50, verbose_name='Remuneration tax additional discount for disabled employee on taxable amount.(%)'),
        ),
        migrations.AddField(
            model_name='payrollconfig',
            name='female_remuneration_tax_discount',
            field=models.FloatField(default=10, verbose_name='Discount for female on evaluated remuneration tax. (%)'),
        ),
        migrations.AddField(
            model_name='payrollconfig',
            name='married_remuneration_discount',
            field=models.FloatField(default=300000.0, verbose_name='Remuneration tax discount for married employee on taxable amount.'),
        ),
        migrations.AddField(
            model_name='payrollconfig',
            name='unmarried_remuneration_discount',
            field=models.FloatField(default=300000.0, verbose_name='Remuneration tax discount for married employee on taxable amount.'),
        ),
    ]
