# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0182_auto_20161204_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_disabled_person',
            field=models.BooleanField(default=False),
        ),
    ]
