# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-05 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0183_employee_is_disabled_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdeduction',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
