# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0184_auto_20161205_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('tax_deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_details', to='hr.TaxDeduction')),
            ],
        ),
    ]
