# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-05 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0185_taxdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='income_tax',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='tax_details',
            field=models.ManyToManyField(blank=True, to='hr.TaxDetail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='hr.EmployeeFacility'),
        ),
    ]
