# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 07:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_data_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'verbose_name_plural': 'Stock Entries'},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
