# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160605_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryrow',
            name='entry_report_row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.EntryReportRow'),
        ),
    ]
