# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockentryrow_entry_report_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
