# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20160414_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentryrow',
            old_name='stock',
            new_name='opening_stock',
        ),
    ]
