# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20160414_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryrow',
            name='sn',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
