# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_stockentryrow_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryrow',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
            preserve_default=False,
        ),
    ]
