# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_stockentryrow_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentryrow',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
