# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20160416_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentryrow',
            name='opening_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockentryrow',
            name='opening_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
