# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_disbursementdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementParticulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_nrs', models.PositiveIntegerField(blank=True, null=True)),
                ('request_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('request_sdr', models.PositiveIntegerField(blank=True, null=True)),
                ('response_nrs', models.PositiveIntegerField(blank=True, null=True)),
                ('response_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('response_sdr', models.PositiveIntegerField(blank=True, null=True)),
                ('with_held_nrs', models.PositiveIntegerField(blank=True, null=True)),
                ('with_held_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('with_held_sdr', models.PositiveIntegerField(blank=True, null=True)),
                ('disbursement_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='project.DisbursementDetail')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ExpenseCategory')),
            ],
        ),
    ]
