# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementdetail',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
