# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20160703_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_row', to='project.ExpenseCategory'),
        ),
    ]
