# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nprexchange',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npr_exchanges', to='core.Currency'),
        ),
    ]
