# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_budgetallocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudgetAllocation',
            new_name='BudgetAllocationItem',
        ),
    ]
