# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20160518_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
