# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_aid_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocationitem',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
