# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160516_1911'),
        ('project', '0021_auto_20160519_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetReleaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('aid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Aid')),
                ('budget_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BudgetHead')),
                ('fy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FiscalYear')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
