# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 06:09
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import njango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20160520_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', njango.fields.BSDateField(blank=True, default=njango.fields.today, null=True, validators=[core.models.validate_in_fy])),
                ('bank_voucher_no', models.PositiveIntegerField(blank=True, null=True)),
                ('wa_no', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
