# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='project_fy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectFy'),
            preserve_default=False,
        ),
    ]
