# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 09:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20160517_1708'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='targetgroup',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
